### PR TITLE
Add homev2 wifi gps template

### PR DESCRIPTION
**Pull request by felixerdy**
Adds a template to run a GPS aware homev2 box.

### CODE REVIEW

**Comment by robarto** [comment]
Is it possible to choose the measurement interval before revceiving the sketch? In many cases on a mobile sensebox an interval of one second would be very interesting.

**Comment by felixerdy** [comment]
@robarto implemented custom posting interval. Still needs to be implemented in tests

**Comment by synolus-david** [comment]
Shall we merge this first before @Thiemann96 includes the OLED/SD-Card into the Templater? Or is it better to wait and merge all 3?

**Comment by Thiemann96** [comment]
Didnt we agree to have the GPS work over UART because its more reliable ?

**Comment by synolus-david** [comment]
> 
> 
> Didnt we agree to have the GPS work over UART because its more reliable ?

no

**Pull request closed without merging**
